# Generated by Django 5.2.4 on 2025-08-22 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSpiderAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
