# Generated by Django 5.2.4 on 2025-08-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSpiderAPI', '0002_useridentity_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='is_continue_use',
            field=models.BooleanField(default=True),
        ),
    ]
