# Generated by Django 5.2.4 on 2025-08-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSpiderAPI', '0003_useridentity_is_continue_use'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIdentity',
        ),
    ]
